version: '3.8'

services:
  # Serviço MongoDB
  mongodb:
    image: mongo:6.0
    container_name: xrpl-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hugo2003
      MONGO_INITDB_DATABASE: xrpl
    restart: always

  # Serviço Go (Servidor Fiber)
  go_app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: xrpl-go-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:hugo2003@mongodb:27017/xrpl?authSource=admin
      WEBSOCKET_URL: wss://s1.ripple.com/
    restart: always

volumes:
  mongodb_data:
